Bank/Bank/Models/TransactionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Bank.Models
{
   
        public class TransactionViewModel
        {
        [Required]
        [Display(Name = "Счет назначения")]
        public string? DistId{ get; set; }

        public int SourceAccountId { get; set; }

            [Required]
            [Display(Name = "Счет назначения")]
            public int DestinationAccountId { get; set; }

            [Required]
            [Range(0.01, double.MaxValue, ErrorMessage = "Введите сумму больше нуля")]
        [Display(Name = "Сумма")]
        public decimal Amount { get; set; }

            [Required]
            [Display(Name = "Тип транзакции")]
            public string TransactionType { get; set; } // "Withdraw" или "Deposit"

            [StringLength(500, ErrorMessage = "Описание не должно превышать 500 символов")]
        [Display(Name = "Описание")]
        public string? Description { get; set; }

            public SelectList ClientAccounts { get; set; }
        }
    
}

Bank/Bank/Controllers/TransactionController.cs
using Bank.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System;

namespace Bank.Controllers
{
    public class TransactionController : Controller
    {
        public IActionResult Index4()
        {
            return View();
        }

        public IActionResult Index5()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index1()
        {
            return View();
        }

        public IActionResult Index2()
        {
            return View();
        }

        public IActionResult Index3()
        {
            return View();
        }

        private readonly BankContext _context;

        public TransactionController(BankContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Create(int? accountId)
        {
            if (accountId == null)
            {
                return BadRequest("ID счета обязателен.");
            }

            var account = _context.Счета.Find(accountId);
            if (account == null)
            {
                return NotFound("Счет не найден.");
            }

            var clientAccounts = _context.Счета.Where(a => a.ID_Клиента == account.ID_Клиента).ToList();

            var viewModel = new TransactionViewModel
            {
                SourceAccountId = account.ID_Счета,
                ClientAccounts = new SelectList(clientAccounts, "ID_Счета", "НомерСчета")
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(TransactionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                //return RedirectToAction("Index", "Account", new { id = model.SourceAccountId });
                var sourceAccount = _context.Счета.FirstOrDefault(a => a.ID_Счета == model.SourceAccountId);
                var destinationAccount = _context.Счета.FirstOrDefault(a => a.ID_Счета == model.DestinationAccountId);

                if (model.SourceAccountId == model.DestinationAccountId)
                {
                    return RedirectToAction("Index3");
                }

                if (model.Amount <= 0)
                {
                    return RedirectToAction("Index1");
                }

                if (model.Amount > destinationAccount.Баланс && model.TransactionType == "Deposit")
                {
                    return RedirectToAction("Index2");
                }

                if (sourceAccount == null || destinationAccount == null)
                {
                    return NotFound("Счет не найден.");
                }

                if (sourceAccount.Баланс < model.Amount && model.TransactionType == "Withdraw")
                {
                    return RedirectToAction("Index");
                }

                if (model.TransactionType == "Withdraw")
                {
                    sourceAccount.Баланс -= model.Amount;
                    destinationAccount.Баланс += model.Amount;
                }
                else if (model.TransactionType == "Deposit")
                {
                    sourceAccount.Баланс += model.Amount;
                    destinationAccount.Баланс -= model.Amount;
                }

                var transaction = new Транзакция
                {
                    ID_Счета = model.SourceAccountId,
                    ДатаТранзакции = DateTime.Now,
                    ТипТранзакции = model.TransactionType,
                    Сумма = model.Amount,
                    Описание = model.Description
                };

                _context.Транзакции.Add(transaction);
                await _context.SaveChangesAsync();

                return RedirectToAction("Profile", "Account", new { id = sourceAccount.ID_Клиента });
            }
            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public IActionResult CreatA(int? accountId)
        {
            if (accountId == null)
            {
                return BadRequest("ID счета обязателен.");
            }

            var account = _context.Счета.Find(accountId);
            if (account == null)
            {
                return NotFound("Счет не найден.");
            }

            var clientAccounts = _context.Счета.Where(a => a.ID_Клиента == account.ID_Клиента).ToList();

            var viewModel = new TransactionViewModel
            {
                SourceAccountId = account.ID_Счета,
                ClientAccounts = new SelectList(clientAccounts, "ID_Счета", "НомерСчета")
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> CreatA(TransactionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.TransactionType = "Withdraw";
                var sourceAccount = _context.Счета.FirstOrDefault(a => a.ID_Счета == model.SourceAccountId);
                var destinationAccount = _context.Счета.FirstOrDefault(a => a.НомерСчета == model.DistId);

                if (model.SourceAccountId == model.DestinationAccountId)
                {
                    return RedirectToAction("Index3");
                }

                if (model.Amount <= 0)
                {
                    return RedirectToAction("Index1");
                }
                //if (model.Amount > destinationAccount.Баланс && model.TransactionType == "Deposit")
                //{
                 //   return RedirectToAction("Index2");

               // }
                if (sourceAccount == null || destinationAccount == null)
                {
                    return RedirectToAction("Index5");
                }

                if (sourceAccount.Баланс < model.Amount && model.TransactionType == "Withdraw")
                {
                    return RedirectToAction("Index");
                }

                if (model.TransactionType == "Withdraw")
                {
                    sourceAccount.Баланс -= model.Amount;
                    destinationAccount.Баланс += model.Amount;
                }
                //else if (model.TransactionType == "Deposit")
                //{
                //    sourceAccount.Баланс += model.Amount;
                //    destinationAccount.Баланс -= model.Amount;
                //}

                var transaction = new Транзакция
                {
                    ID_Счета = model.SourceAccountId,
                    ДатаТранзакции = DateTime.Now,
                    ТипТранзакции = model.TransactionType,
                    Сумма = model.Amount,
                    Описание = model.Description
                };

                _context.Транзакции.Add(transaction);
                await _context.SaveChangesAsync();

                return RedirectToAction("Profile", "Account", new { id = sourceAccount.ID_Клиента });
            }

            return View(model);
        }

        [Authorize]
        public IActionResult TransHistory(int clientId)
        {
            var transactions = _context.Транзакции
                .Include(t => t.Счет)
                .Where(t => t.Счет.ID_Клиента == clientId)
                .ToList();

            return View(transactions);
        }
    }
 }

Bank/Bank/Views/Transaction/CreatA.cshtml
@model TransactionViewModel;
<h2>Создание Транзакции</h2>
<link rel="stylesheet" href="~/css/Trans.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal form-container">
        <hr />

        @Html.HiddenFor(model => model.SourceAccountId)

        <div class="form-group row">
            @Html.LabelFor(model => model.DistId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DistId, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 3 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/Create.cshtml
@model TransactionViewModel

<h2 class="text-center">Создание Транзакции</h2>
<link rel="stylesheet" href="~/css/Trans.css" asp-append-version="true" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-container mt-4">
        @Html.HiddenFor(model => model.SourceAccountId)

        <div class="form-group row">
            @Html.LabelFor(model => model.DestinationAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DestinationAccountId, Model.ClientAccounts, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinationAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TransactionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TransactionType, new SelectList(new List<SelectListItem>
            {
            new SelectListItem { Text = "Перевод", Value = "Withdraw" },
            new SelectListItem { Text = "Пополнение", Value = "Deposit" }
            }, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TransactionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-10 offset-md-2">
                <input type="submit" value="Создать" class="btn btn-primary" />
                <a href="javascript:history.back()" class="btn btn-secondary ml-2">Назад</a>
            </div>
        </div>
    </div>
}

<a href="@Url.Action("CreatA", "Transaction", new { accountId = Model.SourceAccountId })" class="btn btn-success mt-3">Перевести на чужой счет</a>

Bank/Bank/Views/Transaction/Index.cshtml
@{
    ViewData["Title"] = "ER";
}
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
<h1 style="color: red;">
    Подозрительные действия. Транзакция запрещена. Причина: сумма перевода больше чем баланс счета
</h1>
<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/Index1.cshtml
@{
    ViewData["Title"] = "ER";
}
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
<h1 style="color: red;">
    Подозрительные действия. Транзакция запрещена. Причина: попытка перевода недействительной суммы
</h1>
<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/Index2.cshtml
@{
    ViewData["Title"] = "ER";
}
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
<h1 style="color: red;">
    Подозрительные действия. Транзакция запрещена. Причина: на счете вывода недостаточно средств
</h1>
<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/Index3.cshtml
@{
    ViewData["Title"] = "ER";
}
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
<h1 style="color: orangered;">
    Транзакция отменена. Причина: счет пополнения и счет вывода равны
</h1>
<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/Index4.cshtml
@{
    ViewData["Title"] = "Чем отличаются";
}
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/PP.css" asp-append-version="true" />
<div class="content">
    <h1>Текущий счет</h1>
    <p>
        Текущий счет - вид счетов в банках, которые служат для хранения денежных средств и осуществления текущих расчетов предприятиями, организациями и т.п., которые могут быть легко сняты со счета. На Т.С. сосредотачиваются главным образом временно свободные денежные капиталы и кассовые резервы промышленных и торговых предприятий. Расчеты по Т.С. совершаются с помощью чеков. Если на счете отражаются еще и ссудные операции, он называется контокоррентным.
      
    </p>
</div>

<div class="content">
    <h1>Сберегательный счет</h1>
    <p>
        Сберегательный счет - это депозитный счет, на который начисляются проценты, открытый в банке или другом финансовом учреждении. Хотя на этих счетах обычно выплачивается лишь умеренная процентная ставка, их безопасность и надежность делают их хорошим вариантом для хранения наличных, которые вы хотите использовать на краткосрочные нужды. Но учтите, что вывести со счета средства можно лишь через месяц.

    </p>
</div>
<div class="content">
    <h1>Накопительный счет</h1>
    <p>
        Накопительный счёт — это счет, который можно пополнять на любую сумму, а также свободно её снимать, процентный доход начисляется в основном на ту часть денег, которая пролежала на счету месяц.

    </p>
</div>

<div class="content">
    <h1>Кредитный счет</h1>
    <p>
        Кредитный счет- это счет, на который банк зачисляет средства, предоставляемые клиенту в кредит. Кредитный счет может существовать только в одном экземпляре.
    </p>
</div>


<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/Index5.cshtml
@{
    ViewData["Title"] = "ER";
}
<link rel="stylesheet" href="~/css/java.css" asp-append-version="true" />
<h1 style="color: orangered;">
    Транзакция отменена. Причина: счет не найден
<a href="javascript:history.back()" class="btn btn-secondary btn-back">Назад</a>

Bank/Bank/Views/Transaction/TransHistory.cshtml
@model IEnumerable<Bank.Models.Транзакция>
<link rel="stylesheet" href="~/css/Profile.css" asp-append-version="true" />
<h2>История Транзакций Клиента</h2>

<table class="table">
    <thead>
        <tr>
            
            <th>Номер Счета</th>
            <th>Дата Транзакции</th>
            <th>Тип Транзакции</th>
            <th>Сумма</th>
            <th>Описание</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var транзакция in Model)
        {
            <tr>
                
                <td>@транзакция.Счет.НомерСчета</td>
                <td>@транзакция.ДатаТранзакции.ToShortDateString()</td>
                <td>@транзакция.ТипТранзакции</td>
                <td>@транзакция.Сумма</td>
                <td>@транзакция.Описание</td>
            </tr>
        }
    </tbody>
</table>