Bank/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace Bank.Models
{
    public class Contact
    {
        [Display(Name = "Введите имя")]
        [Required(ErrorMessage = "Обязательно введите имя")]
        public string Name { get; set; }

        [Display(Name = "Введите фамилию")]
        [Required(ErrorMessage = "Обязательно введите фамилию")]
        public string Surname { get; set; }

        [Display(Name = "Введите почту")]
        [Required(ErrorMessage = "Обязательно введите почту")]
        [EmailAddress(ErrorMessage = "Неверный формат почты")]
        public string Email { get; set; }
        [Display(Name = "Введите телефон, который привязан к счету")]
        [Required(ErrorMessage = "Обязательно введите телефон")]
        public string Phone { get; set; }
        [Display(Name = "Введите адрес")]
        [Required(ErrorMessage = "Обязательно введите адрес")]
        public string Address { get; set; }
       
        [Display(Name = "Введите возраст")]
        [Required(ErrorMessage = "Обязательно введите возраст")]
        public int Age { get; set; }
       
        [Display(Name = "Что вы хотите спросить? Напишите :)")]
        [Required(ErrorMessage = "Обязательно введите вопрос")]
        [StringLength(6000, ErrorMessage="Превышено количество символов >6000")]
        public string Message {  get; set; }

    }
}

Bank/Models/ErrorViewModel.cs
namespace Bank.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bank/Controllers/ContactsController.cs
using Bank.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Mail;
using System.Net;

namespace Bank.Controllers
{
   
        public class ContactsController : Controller
        {
            private readonly ILogger<ContactsController> _logger;

            public ContactsController(ILogger<ContactsController> logger)
            {
                _logger = logger;
            }

            public IActionResult Index()
            {
                return View();
            }

        [HttpPost]
        public IActionResult Check(Contact contact)
        {
            if (ModelState.IsValid)
            {









                string smtpServer = "smtp.mail.ru";
                int smtpPort = 587; // Обычно используется порт 587 для TLS
                string smtpUsername = "arina_andrey2004@mail.ru";
                string smtpPassword = "WdR03VPBFFgBeBG66HPu"; // замените на ваш реальный пароль

                // Создаем объект клиента SMTP
                using (SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort))
                {
                    // Настройка аутентификации
                    smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                    smtpClient.EnableSsl = true;

                    using (MailMessage mailMessage = new MailMessage())
                    {
                        mailMessage.From = new MailAddress(smtpUsername);
                        mailMessage.To.Add("venesken@mail.ru"); // Укажите адрес получателя
                        mailMessage.Subject = "Обратная связь";
                        mailMessage.Body = $"Имя: {contact.Name} \r\n Фамилия: {contact.Surname}\r\n Почта: {contact.Email}\r\n Телефон: {contact.Phone}\r\n Адрес: {contact.Address}\r\n Сообщение: {contact.Message}  ";

                        try
                        {
                            // Отправляем сообщение
                            smtpClient.Send(mailMessage);
                            Console.WriteLine("Сообщение успешно отправлено.");
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Ошибка отправки сообщения: {ex.Message}");
                        }
                    }
                    using (MailMessage mailMessage = new MailMessage())
                    {
                        mailMessage.From = new MailAddress(smtpUsername);
                        mailMessage.To.Add($"{contact.Email}"); // Укажите адрес получателя
                        mailMessage.Subject = "Обратная связь";
                        mailMessage.Body = $"Здравствуйте {contact.Name}, спасибо, что обратились в службу поддержки, ваше сообщение получено,\n ближайший свободный оператор ответит вам, а пока проверьте правильность введенных данных\n Имя {contact.Name} \r\n Фамилия: {contact.Surname}\r\n Почта: {contact.Email}\r\n Телефон: {contact.Phone}\r\n Адрес: {contact.Address}";
                        
                        try
                        {
                            // Отправляем сообщение
                            smtpClient.Send(mailMessage);
                            Console.WriteLine("Сообщение успешно отправлено.");
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Ошибка отправки сообщения: {ex.Message}");
                        }
                    }
                }

















                return RedirectToAction("ThankYou");
            }
            return View("Index");
        }

        public IActionResult ThankYou()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
            public IActionResult Error()
            {
                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }
    }

Bank/Views/Contacts/Index.cshtml
@model Contact
@{
    ViewData["Title"] = "Обратная связь";
}

<h1>
    Обратная связь 
</h1>

<form method="post" asp-controller="Contacts" asp-action="Check">

    <label asp-for="Name"></label>
    <input asp-for="Name"/>
    <span asp-validation-for="Name"></span>

    <label asp-for="Surname"></label>
    <input asp-for="Surname" />
    <span asp-validation-for="Surname"></span>


    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <span asp-validation-for="Email"></span>

    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <span asp-validation-for="Phone"></span>

    <label asp-for="Address "></label>
    <input asp-for="Address " />
    <span asp-validation-for="Address "></span>


    <label asp-for="Age"></label>
    <input asp-for="Age" />
    <span asp-validation-for="Age"></span>


    <label asp-for="Message"></label>
    <textarea asp-for="Message" class="large-textarea"></textarea>
    <span asp-validation-for="Message"></span>

    <input type="submit" value="Отправить" />
</form>

Bank/Views/Contacts/ThankYou.cshtml
@{
    ViewData["Title"] = "Обратная связь";
}
<h1>
    Спасибо! Мы ответим вам как можно быстрее
</h1>

Bank/Views/Home/PrivacyPolicy.cshtml
@{
    ViewData["Title"] = "Политика конфединциальности";
}
<link rel="stylesheet" href="~/css/PP.css" asp-append-version="true" />
<div class="content">
    <h1>Политика конфиденциальности</h1>
    <p>
        Настоящая политика конфиденциальности (далее — Политика) действует в отношении всей информации, включая персональные данные в понимании применимого законодательства (далее — «Персональная информация»), которую ООО «BANK» и/или его аффилированные лица, в том числе входящие в одну группу с ООО «BANK» (далее — «Bank»), могут получить о Вас в процессе использования Вами любых сайтов, программ, продуктов и/или сервисов Bankа (далее вместе — «Сервисы»), информацию о которых Вы можете найти на сайтах bank.ru, bank.com, bank.by, bank.kz, bank.com.tr, bank.co.il и других принадлежащих Bankу сайтах (далее вместе — «Сайты»), а также в ходе исполнения Bankом / его аффилированными лицами любых соглашений и договоров, заключенных с Вами в связи с использованием Вами Сервисов. Bank может также получать Персональную информацию от своих партнеров (далее — «Партнеры»), сайты, программы, продукты или сервисы которых Вы используете (например, от рекламодателей Bankа или служб такси), из других источников с общедоступными персональными данными. В соответствующих случаях передача Персональной информации возможна только в случаях, установленных применимым законодательством, и осуществляется на основании специальных договоров между Bankом и каждым из Партнеров.

        Пожалуйста, обратите внимание, что использование любого из Сайтов и/или Сервисов может регулироваться дополнительными условиями, которые могут вносить в настоящую Политику изменения и/или дополнения, и/или иметь специальные условия в отношении персональной информации, размещенные в соответствующих разделах документов для таких Сайтов и/или Сервисов.
    </p>
</div>

Bank/Views/Home/Uslov.cshtml
@{
    ViewData["Title"] = "Условия использования";
}
<link rel="stylesheet" href="~/css/PP.css" asp-append-version="true" />
<div class="content">
    <h1>Условия использования</h1>
   <p>

        1.1. ООО «BANK» (далее — «Bank») предлагает пользователю сети Интернет (далее — Пользователь) использовать сервис Bank ID (далее — «Сервис»), предоставляющий возможность создания и управления учетной записью (Bank ID) для использования сервисов, предоставляемых ООО «BANK» и/или его аффилированными лицами, в том числе входящими в одну группу с ООО «BANK» (далее — «сервисы Bankа»), а также предоставляющий отдельные функции в соответствии с настоящими Условиями использования сервиса Bank ID (далее — «Условия»).

        1.2. Настоящие Условия представляют собой дополнение и неотъемлемую часть Пользовательского соглашения сервисов Bank относительно порядка использования сервисов Bankа.

        Во всем, что не предусмотрено настоящими Условиями, отношения между Bankом и Пользователем в связи с использованием Bank ID регулируются:

        Пользовательским соглашением сервисов Bankа
        Политикой конфиденциальности (далее — «Регулирующие документы»).
        1.3. Начиная использовать Сервис/его отдельные функции, Пользователь считается принявшим настоящие Условия, а также условия всех указанных выше документов, в полном объеме, без всяких оговорок и исключений. В случае несогласия Пользователя с какими-либо из положений указанных документов, Пользователь не вправе использовать Сервис.

        1.4. Настоящие Условия могут быть изменены Bankом без какого-либо специального уведомления, новая редакция Условий вступает в силу с момента ее размещения в сети Интернет по указанному в настоящем абзаце адресу, если иное не предусмотрено новой редакцией Условий. Действующая редакция Условий всегда находится на странице по адресу:

        1.5. В случае если Bankом были внесены какие-либо изменения в настоящие Условия, в порядке, предусмотренном п. 1.4. настоящих Условий, с которыми Пользователь не согласен, он обязан прекратить использование Сервиса


   </p>
</div>

Bank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bank</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>




        <a href="/Home" class="logo">
            Bank
            <img src="/favicon-32x32.png" alt="Logo" style="width: 25px; height: 25px; vertical-align: middle;">
        </span>
        <nav>
            <a href="/Home">Главная</a>
            <a href="/contacts/Index" class="contact">Обратная связь</a>
        </nav>
            







    </header>






   <main>
       @RenderBody()
   </main>
   
    <footer>
        <p>&copy; 2024 ООО Bank. Все права защищены.</p>
        <p><a href="/Home/PrivacyPolicy" class="footer-link">Политика конфиденциальности</a> | <a href="/Home/Uslov" class="footer-link">Условия использования</a></p>
        <a href="tel:+79143991617" class="phone-link">+7 (914) 399-1617</a>
    </footer>


</body>
</html>